# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=400)),
                ('capital', models.CharField(max_length=400)),
                ('language', models.CharField(max_length=400)),
                ('habitants', models.CharField(max_length=400)),
                ('continent', models.CharField(max_length=255)),
                ('square_kilometers', models.CharField(max_length=255)),
            ],
        ),
    ]
